server:
  port: 9094

eureka:
  client:
    service-url:
      # Change default-zone to defaultZone
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    # Crucial for Docker: Use the container name for registration
    prefer-ip-address: true 
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: ORDER-SERVICE

  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:admin}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/order_db?authSource=admin
      auto-index-creation: true

  docker:
    compose:
      enabled: false
      lifecycle-management: start-only

# 1. Expose the endpoint over the web
management:
  endpoints:
    web:
      exposure:
        include: health,info

  # 2. Enable the Java and Env info contributors (Disabled by default in 3.x)
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Custom path for Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
# Include Actuator endpoints in the documentation
  show-actuator: true

# Package to scan for controllers
  packages-to-scan: com.codiecode.order.controller